apiVersion: v1
stringData:
  POSTGRES_PASSWORD: J48hVdb8lYSjyksp12asPftr0K8yNH0R3FDzVxKto3fKrcVQ98XpJU1TU6caYg5Y
  DATABASE_URL: postgresql://bsbingo:J48hVdb8lYSjyksp12asPftr0K8yNH0R3FDzVxKto3fKrcVQ98XpJU1TU6caYg5Y@postgres/bsbingo
  DJANGO_SECRET_KEY: NqFDpNCazOPjvPGOdp4BbWC8tCRpY2KnSRt63cAaq6tAN7EbnF4MDg7DsxDPG2t6
kind: Secret
metadata:
  name: secrets-config
type: Opaque
