# Generated by Django 6.0.7 on 2026-07-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bingo", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="boardsquare",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 0), ("position__lte", 24)),
                name="position_range",
            ),
        ),
    ]
