apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DJANGO_DEBUG: "False"
  USE_DOCKER: "yes"
  DJANGO_ADMIN_URL: "admin/"
  DJANGO_SETTINGS_MODULE: "config.settings.local"
  DJANGO_SECRET_KEY: "CHANGEME"
  DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,backend,.bs-bingo.app"
  DJANGO_CSRF_TRUSTED_ORIGINS: "http://localhost,https://bs-bingo.app"
  DJANGO_SECURE_SSL_REDIRECT: "False"
  PGDATA: "/var/lib/postgresql/data/pgdata"
  POSTGRES_DB: "bsbingo"
  POSTGRES_USER: "bsbingo"
  REDIS_URL: "redis://redis:6379/1"
  # S3 storage access
  DJANGO_AWS_REGION_NAME: "us-east-1"
  DJANGO_AWS_STORAGE_BUCKET_NAME: "CHANGEME_S3_BUCKET_NAME"

